[LOGGER]
LEVEL = 0                           # Default Level

[LOGGER.PGTUNER_DBA.INFO_ROTATION_FILE_HANDLER]
ENABLED = false
ENCODING = "utf-8"
DELAY = false
ERRORS = "None"
LEVEL = 20
HANDLER_TYPE = "TimedRotatingFileHandler"
LOG_FILE_EXTENSION = "log"
LOG_FILE_PATH = "log/pgtunerdba_info_timedrotate"
LOG_FILEMODE = "a"
LOG_ROTATE_WITH_DATE_ONLY = false
LOG_ROTATE_WITH_DATE_TIME = false
LOG_FORMAT = "[%(name)s-INFO_TIMED_ROTATE] [%(asctime)s] %(levelname)s: %(message)s"
WHEN = 'd'
INTERVAL = 1    # 1 day
BACKUP_COUNT = 14   # Keep for 14 days
COMPRESSION = 'gzip:6'


[LOGGER.PGTUNER_DBA.DEBUG_FILE_HANDLER]
ENABLED = false
ENCODING = "utf-8"
DELAY = false
ERRORS = "None"
LEVEL = 10
HANDLER_TYPE = "FileHandler"
LOG_FILE_EXTENSION = "log"
LOG_FILE_PATH = "log/pgtuner_debug"
LOG_FILEMODE = "a"
LOG_ROTATE_WITH_DATE_ONLY = false
LOG_ROTATE_WITH_DATE_TIME = true
LOG_FORMAT = "[%(name)s-DEBUGFILE] [%(asctime)s] [%(levelname)s] [File=%(pathname)s ; Line=%(lineno)d]: %(message)s"


[LOGGER.PGTUNER_DBA.INFO_STREAM_HANDLER]
ENABLED = false
LEVEL = 20
STREAM = "ext://sys.stdout"
LOG_FORMAT = "[%(name)s-OUTSTREAM] [%(asctime)s] %(levelname)s: %(message)s"

[LOGGER.PGTUNER_DBA.ERR_STREAM_HANDLER]
ENABLED = false
LEVEL = 40
STREAM = "ext://sys.stderr"
LOG_FORMAT = "[%(name)s-ERRSTREAM] [%(asctime)s] %(levelname)s: %(message)s"
