[LOGGER]
LEVEL = 10                           # Default Level

[LOGGER.PGTUNER.INFO_ROTATION_FILE_HANDLER]
ENABLED = false
ENCODING = "utf-8"
DELAY = false
ERRORS = "None"
LEVEL = 20
HANDLER_TYPE = "TimedRotatingFileHandler"
LOG_FILE_EXTENSION = "log"
LOG_FILE_PATH = "log/pgtuner_info_timedrotate"
LOG_FILEMODE = "a"
LOG_ROTATE_WITH_DATE_ONLY = false
LOG_ROTATE_WITH_DATE_TIME = false
LOG_FORMAT = "[%(name)s] [%(asctime)s] %(levelname)s: %(message)s"
WHEN = 'd'
INTERVAL = 1    # 1 day
BACKUP_COUNT = 14   # Keep for 14 days
COMPRESSION = 'gzip:6'

[LOGGER.PGTUNER.INFO_STREAM_HANDLER]
ENABLED = true
LEVEL = 20
STREAM = "ext://sys.stdout"
LOG_FORMAT = "[%(name)s] [%(asctime)s] %(levelname)s: %(message)s"

[LOGGER.PGTUNER.ERR_STREAM_HANDLER]
ENABLED = false
LEVEL = 40
STREAM = "ext://sys.stderr"
LOG_FORMAT = "[%(name)s] [%(asctime)s] %(levelname)s: %(message)s"
