[LOGGER]
LEVEL = 10                           # Default Level

[LOGGER.PGTUNER_DBA.DEBUG_FILE_HANDLER]
ENABLED = true
ENCODING = "utf-8"
DELAY = false
ERRORS = "None"
LEVEL = 10
HANDLER_TYPE = "FileHandler"
LOG_FILE_EXTENSION = "log"
LOG_FILE_PATH = "log/pgtuner_debug"
LOG_FILEMODE = "a"
LOG_ROTATE_WITH_DATE_ONLY = false
LOG_ROTATE_WITH_DATE_TIME = true
LOG_FORMAT = "[%(name)s-DEBUGFILE] [%(asctime)s] [%(levelname)s] [File=%(pathname)s ; Line=%(lineno)d]: %(message)s"


[LOGGER.PGTUNER_DBA.ERROR_ROTATION_FILE_HANDLER]
ENABLED = false
ENCODING = "utf-8"
DELAY = false
ERRORS = "None"
LEVEL = 40
HANDLER_TYPE = "RotatingFileHandler"
LOG_FILE_EXTENSION = "log"
LOG_FILE_PATH = "log/pgtunerdba_error_rotate"
LOG_FILEMODE = "a"
LOG_ROTATE_WITH_DATE_ONLY = false
LOG_ROTATE_WITH_DATE_TIME = false
LOG_FORMAT = "[%(name)s-ERROR_ROTATE] [%(asctime)s] %(levelname)s: %(message)s"
MAX_BYTES = 67108864          # 64 MB
BACKUP_COUNT = 30
COMPRESSION = 'gzip:9'

[LOGGER.PGTUNER_DBA.OUT_STREAM_HANDLER]
ENABLED = true
LEVEL = 10
STREAM = "ext://sys.stdout"
LOG_FORMAT = "[%(name)s-OUTSTREAM] [%(asctime)s] %(levelname)s: %(message)s"
