[pgtuner_dba]

[pgtuner_dba.memory_ratio]
# This section is for memory ratio. The ratio is used to determine the number of CPU cores that should be allocated
# for a given amount of memory. The ratio is used to determine the number of CPU cores that should be allocated for a
# given amount of memory. For most cloud-provider database instance, the most used ratio is 4 (general-purpose) and
# 8 (memory-optimized), and lower ratio than general-purpose is rare to nothing. Most cloud providers has CPU capped
# at 96 vCores
genaral_purpose = 4
semi_memory_optimized = 6               # Custom for some specific instances
memory_optimized = 8
hyper_memory_optimized = 12             # Mostly used for large data warehouses, OLAP systems and Oracle DB

[pgtuner_dba.profile]



